name: C++ CI Clang-19

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: deps
      run: |
        sudo apt-get install checkinstall pybind11-dev libpq-dev libc++-19-dev clang-19 libpcap-dev
        sudo apt-get purge libc++-18-dev clang-18
        git clone https://github.com/jtv/libpqxx
        mkdir libpqxx/build
        pushd libpqxx/build
        CC=clang-20 CXX=clang++-19 CXXFLAGS=" -stdlib=libc++ " cmake .. -DBUILD_TEST=OFF -DBUILD_SHARED_LIBS=on -DCMAKE_CXX_STANDARD=26
        CC=clang-20 CXX=clang++-19 CXXFLAGS=" -stdlib=libc++ " make -j `nproc`
        sudo checkinstall
        popd
    - name: make
      run: |
         CXXFLAGS=" -DSKIP_CONSTEXPR_TESTS " make 

      
