name: C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: deps
      run: |
        sudo apt-get purge libc++-18-dev clang-18
        sudo apt-get install checkinstall pybind11-dev libpq-dev libc++-20-dev clang-20 libpcap-dev
        git clone https://github.com/jtv/libpqxx
        mkdir libpqxx/build
        pushd libpqxx/build
        CC=clang-20 CXX=clang++-20 CXXFLAGS=" -stdlib=libc++ " cmake .. -DBUILD_TEST=OFF -DBUILD_SHARED_LIBS=on -DCMAKE_CXX_STANDARD=26
        CC=clang-20 CXX=clang++-20 CXXFLAGS=" -stdlib=libc++ " make -j `nproc`
        sudo checkinstall
        popd
    - name: make
      run: |
        CC=clang-20 CXX=clang++-20 CXXFLAGS=" -DSKIP_CONSTEXPR_TESTS " make -j `nproc` bin/graph bin/demo bin/live bin/classic bin/psqlsensor

      
