name: C++ CI Clang-19

on:
  release:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: deps
      run: |
        sudo apt-get purge libc++-18-dev clang-18
        sudo apt-get install checkinstall pybind11-dev libpq-dev libc++-19-dev clang-19 libpcap-dev
        git clone https://github.com/jtv/libpqxx
        mkdir libpqxx/build
        pushd libpqxx/build
        CC=clang-19 CXX=clang++-19 CXXFLAGS=" -stdlib=libc++ " cmake .. -DBUILD_TEST=OFF -DBUILD_SHARED_LIBS=off -DCMAKE_CXX_STANDARD=26
        CC=clang-19 CXX=clang++-19 CXXFLAGS=" -stdlib=libc++ " make -j `nproc`
        sudo checkinstall
        popd
    - name: make
      run: |
         CC=clang-19 CXX=clang++-19 CXXFLAGS=" -DSKIP_CONSTEXPR_TESTS " make m=portable -j `nproc` bin/bandwidthd bin/live bin/graph bin/psqlsensor

    - name: Package artifacts
      run: |
        cd build/portable
        zip -r portable-binaries.zip bin
    - name: Upload portable binaries to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/portable/portable-binaries.zip
        asset_name: portable-binaries.zip
        asset_content_type: application/zip

      
